In [1]:
import numpy as np
from becquerel import rebin

Rebin can take in numpy arrays (both 1D and 2D, with the shape (number of spectra, number of bins) directly:

In [2]:
in_spectrum_1D = np.array([1,2,2,3,1,0])
in_edges = np.array([0,2,4,6,8,10,12])
out_edges = np.array([0,1,3,6,7,9])  # The edges does not have to be equally spaced

TODO: rebinning spectrum objects

## Rebinning methods

there are two rebinning methods, `interpolation` and `listmode`  
- `interpolation`: assuming that the distribution within each bin is flat (or as specified in the `slopes` argument), put the proportion of counts into each of the corresponding new bins. Counts may become fractional after the rebinning, and this does not preserve Poisson statistics. (TODO: add how the `slopes` argument works)
- `listmode`: carries out a stochastic rebinning, by randomly sampling energies within each bin and binning all these energies into the new bin structure

In [3]:
rebin(in_spectrum_1D, in_edges, out_edges, method='interpolation', slopes=None)

array([ 0.5,  1.5,  3. ,  1.5,  2.5])

In [4]:
rebin(in_spectrum_1D, in_edges, out_edges, method='listmode', slopes=None)

array([1, 0, 4, 2, 2])

### 2D Rebinning
You can rebin multiple spectra at the same time, too. The example uses the same input bin edges as the 1D example.

In [5]:
in_spectrum_2D = np.array([[1,2,2,3,1,0], [1,1,5,2,6,3], [5,7,1,3,2,8]])
out_edges = np.arange(15)

In [6]:
rebin(in_spectrum_2D, in_edges, out_edges, method='interpolation', slopes=None)

array([[ 0.5,  0.5,  1. ,  1. ,  1. ,  1. ,  1.5,  1.5,  0.5,  0.5,  0. ,
         0. ,  0. ,  0. ],
       [ 0.5,  0.5,  0.5,  0.5,  2.5,  2.5,  1. ,  1. ,  3. ,  3. ,  1.5,
         1.5,  0. ,  0. ],
       [ 2.5,  2.5,  3.5,  3.5,  0.5,  0.5,  1.5,  1.5,  1. ,  1. ,  4. ,
         4. ,  0. ,  0. ]])

In [7]:
rebin(in_spectrum_2D, in_edges, out_edges, method='listmode', slopes=None)

array([[1, 0, 1, 1, 1, 1, 1, 2, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 4, 1, 2, 0, 5, 1, 0, 3, 0, 0],
       [1, 4, 4, 3, 1, 0, 1, 2, 1, 1, 5, 3, 0, 0]])

TODO: add graphs